export const render = (entries,repo) => {
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const link=(url,label)=>`<a href="${esc(url)}">${esc(label)}</a>`;
const list=xs=>`<ul>${xs.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`;
return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>New Haven Civic Data Directory</title><meta name="description" content="Find New Haven civic data, access instructions, contacts and known gaps."><link rel="stylesheet" href="style.css"></head><body>
<a class="skip" href="#directory">Skip to directory</a>
<header><p class="eyebrow">A community resource</p><h1>New Haven Civic Data Directory</h1><p>Find city data. Understand how to use it. Help fill the gaps.</p><nav aria-label="Project">${link(repo,"Repository")} ${link(repo+"/issues/new?template=data-request.yml","Request data")} ${link(repo+"/blob/main/ROADMAP.md","Investigation roadmap")}</nav></header>
<main><section aria-labelledby="directory-heading" id="directory"><h2 id="directory-heading">Browse sources</h2><p>These entries point to original sources. Each records the access checked and questions still open. “Access tested” may mean a page or metadata was inspected; read the entry for its exact scope.</p>
<div id="filters" hidden><label>Search sources <input id="search" type="search" placeholder="Try parcels, budgets or agendas"></label><label>Category <select id="category"><option value="">All categories</option>${[...new Set(entries.map(x=>x.category))].sort().map(x=>`<option>${esc(x)}</option>`).join("")}</select></label></div>
<p id="count" role="status" aria-live="polite">${entries.length} sources</p>
<div class="table-wrap" tabindex="0" role="region" aria-label="Data sources table"><table><caption class="sr-only">New Haven civic data sources and access status</caption><thead><tr><th scope="col">Source</th><th scope="col">Category</th><th scope="col">Access</th><th scope="col">Cost</th><th scope="col">Status</th><th scope="col">Checked</th></tr></thead><tbody>${entries.map(x=>`<tr data-source="${esc(x.id)}"><th scope="row"><a href="#${esc(x.id)}">${esc(x.title)}</a><span class="description">${esc(x.description)}</span></th><td>${esc(x.category)}</td><td>${esc(x.access)}</td><td>${esc(x.cost)}</td><td><span class="badge">${esc(x.status)}</span></td><td><time datetime="${esc(x.checked_on)}">${esc(x.checked_on)}</time></td></tr>`).join("")}</tbody></table></div><p id="empty" hidden>No sources match. Clear your search or choose another category.</p></section>
<section aria-labelledby="details-heading"><h2 id="details-heading">Source details</h2>${entries.map(x=>`<article id="${esc(x.id)}" data-entry="${esc(x.id)}"><p class="eyebrow">${esc(x.category)} · ${esc(x.status)}</p><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><p>${link(x.url,"Open source")} · ${link(repo+"/blob/main/sources/"+x.id+".json","View entry in GitHub")}</p><dl><dt>Publisher / host</dt><dd>${esc(x.publisher)}</dd><dt>Source type</dt><dd>${esc(x.source_type)}</dd><dt>Contact</dt><dd>${esc(x.contact)}</dd><dt>Formats</dt><dd>${esc(x.formats.join(", ")||"Not confirmed")}</dd><dt>Cost</dt><dd>${esc(x.cost)}</dd><dt>Reuse terms</dt><dd>${esc(x.terms)}</dd><dt>Update frequency</dt><dd>${esc(x.update_frequency)}</dd><dt>Entry maintainer</dt><dd>${esc(x.entry_maintainer)}</dd><dt>Last checked</dt><dd>${esc(x.checked_on)}; see evidence for scope</dd></dl>
<h4>How to access</h4><ol>${x.steps.map(v=>`<li>${esc(v)}</li>`).join("")}</ol><h4>Key fields</h4>${x.fields.length?`<table><thead><tr><th scope="col">Field</th><th scope="col">Meaning</th></tr></thead><tbody>${x.fields.map(f=>`<tr><th scope="row">${esc(f[0])}</th><td>${esc(f[1])}</td></tr>`).join("")}</tbody></table>`:"<p>Field schema not yet verified.</p>"}
<h4>Known limitations</h4>${list(x.limitations)}<h4>Next investigation</h4>${list(x.next)}${x.related?`<h4>Related sources</h4><ul>${x.related.map(v=>`<li>${link(v.url,v.label)}</li>`).join("")}</ul>`:""}<h4>Check evidence</h4><ul>${x.evidence.map(v=>`<li>${link(v.url,v.note)}</li>`).join("")}</ul><p>${link(repo+"/issues/new?template=source-correction.yml","Report a correction")} · <a href="#directory">Back to directory</a></p></article>`).join("")}</section>
</main><footer><p>Independent community directory. Source publishers maintain their original data; entry maintainers document access. Confirm dates, costs and terms before relying on a source.</p><p>${link(repo+"/blob/main/research/peer-cities.md","Peer-city research")} · ${link("catalog.json","Download directory JSON")}</p></footer>
<script src="search.js" defer></script></body></html>`;
};
