import {READINESS_LABELS,reviewDue} from './readiness.mjs';
import {renderAgentBrief} from './agent-brief.mjs';
const escapeHTML = value => String(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const link = (url, label, className='') => `<a${className ? ` class="${escapeHTML(className)}"` : ''} href="${escapeHTML(url)}">${escapeHTML(label)}</a>`;
const renderStep = (entry, value, index) => {
  let text = escapeHTML(value);
  for (const item of entry.step_links || []) {
    if (item.step === index) text = text.replace(escapeHTML(item.label), link(item.url, item.label));
  }
  return '<li>' + text + '</li>';
};
const list = values => `<ul>${values.map(value => `<li>${escapeHTML(value)}</li>`).join('')}</ul>`;
const readinessLabel = entry => READINESS_LABELS[entry.build_readiness.level];
const reviewFlag = entry => `<span class="review-due" data-review-on="${escapeHTML(entry.build_readiness.next_review_on)}"${reviewDue(entry.build_readiness) ? '' : ' hidden'}>Review due</span>`;
const searchText = entry => [entry.title,entry.description,entry.category,entry.publisher,readinessLabel(entry),entry.build_readiness.summary,entry.build_readiness.preparation.join(' '),entry.access,entry.contact,entry.formats.join(' '),entry.fields.flat().join(' '),entry.steps.join(' '),entry.limitations.join(' '),entry.next.join(' ')].join(' ');
function page({title, repo, prefix='', content, search=false, source=false}) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(title)}</title><meta name="description" content="Find New Haven civic data, access instructions, contacts and known gaps."><link rel="stylesheet" href="${prefix}style.css"></head><body class="${source ? 'source-page' : 'directory-page'}">
<a class="skip" href="#main">Skip to content</a>
<header><div class="masthead"><div class="site-identity">${source ? link(prefix+'index.html','New Haven Civic Data Directory','site-brand') : '<h1 class="site-title"><a class="site-brand" href="index.html">New Haven Civic Data Directory</a></h1>'}<p class="site-subtitle">A community resource for New Haven</p></div><nav class="site-nav" aria-label="Primary"><div class="nav-links"><a href="${prefix}index.html"${source ? '' : ' aria-current="page"'}>Browse sources</a>${link(repo+'/issues','Requests')}${link(repo+'/blob/main/ROADMAP.md','Roadmap')}</div>${link(prefix+'request.html','Request data','button-link')}</nav></div>${source ? `<nav class="breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="${prefix}index.html">Browse sources</a></li><li><span aria-current="page">${escapeHTML(title)}</span></li></ol></nav>` : ''}${source ? `<h1>${escapeHTML(title)}</h1>` : '<p class="directory-intro">Find city data. Understand how to use it. Help fill the gaps.</p>'}</header>
<main id="main">${content}</main><footer><p>Independent community directory. Source publishers maintain their original data; entry maintainers document access. Confirm dates, costs and terms before relying on a source.</p><p>${link(repo,'Repository')} · ${link(repo+'/blob/main/research/peer-cities.md','Peer-city research')} · ${link(prefix+'catalog.json','Download directory JSON')}</p></footer>
${search ? '<script src="search.js" defer></script>' : ''}${source ? '<script src="../agent-brief.js" defer></script>' : ''}<script src="${prefix}readiness.js" defer></script></body></html>`;
}
export function render(entries, repo) {
  const content = `<section aria-labelledby="directory-heading" id="directory"><h2 id="directory-heading">Browse sources</h2><p>These entries point to original sources. Each records the access checked and questions still open. “Access tested” may mean a page or metadata was inspected; open a source for its exact scope.</p>
<div id="filters" hidden><label>Search sources <input id="search" type="search" placeholder="Try parcels, budgets or agendas"></label><label>Category <select id="category"><option value="">All categories</option>${[...new Set(entries.map(entry=>entry.category))].sort().map(category=>`<option>${escapeHTML(category)}</option>`).join('')}</select></label></div>
<p id="count" role="status" aria-live="polite">${entries.length} sources</p><div class="table-wrap" tabindex="0" role="region" aria-label="Data sources table"><table class="directory-table"><caption class="sr-only">New Haven civic data sources and access status</caption><thead><tr><th scope="col">Source</th><th scope="col">Category</th><th scope="col">Data owner / publisher</th><th scope="col">Access</th><th scope="col">Cost</th><th scope="col">Status</th><th scope="col">Checked</th></tr></thead><tbody>
${entries.map(entry=>`<tr data-source="${escapeHTML(entry.id)}" data-category="${escapeHTML(entry.category)}" data-search="${escapeHTML(searchText(entry))}"><th scope="row">${link('sources/'+entry.id+'.html',entry.title)}<span class="listing-readiness">Build readiness: ${escapeHTML(readinessLabel(entry))} ${reviewFlag(entry)}</span></th><td>${escapeHTML(entry.category)}</td><td>${escapeHTML(entry.listing?.publisher || entry.publisher)}</td><td>${escapeHTML(entry.listing?.access || entry.access)}</td><td>${escapeHTML(entry.listing?.cost || entry.cost)}</td><td><span class="badge">${escapeHTML(entry.status)}</span></td><td><time datetime="${escapeHTML(entry.checked_on)}">${escapeHTML(entry.checked_on)}</time></td></tr>`).join('')}
</tbody></table></div><p id="empty" hidden>No sources match. Clear your search or choose another category.</p></section>`;
  return page({title:'New Haven Civic Data Directory',repo,content,search:true});
}
export function renderSource(entry, repo) {
  const definition = (label,value) => `<dt>${escapeHTML(label)}</dt><dd>${escapeHTML(value)}</dd>`;
  const fact = (label,value) => `<div>${definition(label,value)}</div>`;
  const content = `<article class="source-detail"><p class="eyebrow">${escapeHTML(entry.category)} · ${escapeHTML(entry.status)}</p><p class="source-summary">${escapeHTML(entry.description)}</p>
<section aria-labelledby="overview-heading"><h2 id="overview-heading">At a glance</h2><dl class="source-overview">${fact('Access',entry.access)}${fact('Formats',entry.formats.join(', ')||'Not confirmed')}${fact('Data owner / publisher',entry.publisher)}${fact('Last checked',entry.checked_on)}</dl><p class="check-note">Last checked is when this directory verified access, not when the data was updated. See the evidence below for exactly what was checked.</p></section>
<div class="source-actions"><p class="source-link-label">Original source</p><p>${link(entry.url,'View source','button-link')}</p></div>
<section aria-labelledby="access-heading"><h2 id="access-heading">How to access</h2><ol>${entry.steps.map((value,index)=>renderStep(entry,value,index)).join('')}</ol></section>
<section aria-labelledby="readiness-heading" class="source-readiness"><h2 id="readiness-heading">Build readiness</h2><p><span class="readiness-label">${escapeHTML(readinessLabel(entry))}</span> ${reviewFlag(entry)}</p><p>${escapeHTML(entry.build_readiness.summary)}</p><h3>Preparation still needed</h3>${entry.build_readiness.preparation.length ? list(entry.build_readiness.preparation) : '<p>No additional preparation is documented for the tested workflow. Check its scope and limitations before adapting it.</p>'}<p class="check-note">Assessed ${escapeHTML(entry.build_readiness.assessed_on)} · Next review ${escapeHTML(entry.build_readiness.next_review_on)} · Review owner: ${escapeHTML(entry.build_readiness.review_owner)}</p><p class="check-note">This describes the work needed to build with the source. It does not certify accuracy, completeness, freshness or reuse rights. A review-due label means the assessment needs a fresh check.</p><p class="check-note">Based on ${entry.build_readiness.evidence.map((url,index)=>link(url,'source check '+(index+1))).join(', ')}. ${link('../build-readiness.html','What the readiness labels mean')}</p></section>
<section aria-labelledby="agent-heading" class="agent-handoff"><h2 id="agent-heading">Use with your agent</h2><p>Copy this brief into your agent and replace the project description. It links to this entry’s current access instructions and limitations.</p><label for="agent-brief" class="sr-only">Source brief for your agent</label><textarea id="agent-brief" readonly rows="8" spellcheck="false">${escapeHTML(renderAgentBrief(entry))}</textarea><p class="agent-copy-actions"><button type="button" data-copy-brief="agent-brief" data-copy-status="agent-copy-status">Copy agent brief</button> ${link('../sources/'+entry.id+'.json','Read source JSON')}</p><p id="agent-copy-status" role="status" aria-live="polite"></p><p class="check-note">Generated from this entry. Copied text is a dated snapshot; source changes still need verification. You can select and copy the text manually.</p></section>
<section aria-labelledby="limits-heading"><h2 id="limits-heading">Known limitations</h2>${list(entry.limitations)}</section>
<section aria-labelledby="fields-heading"><h2 id="fields-heading">Key fields</h2>
${entry.fields.length ? `<table class="source-fields"><thead><tr><th scope="col">Field</th><th scope="col">Meaning</th></tr></thead><tbody>${entry.fields.map(field=>`<tr><th scope="row">${escapeHTML(field[0])}</th><td>${escapeHTML(field[1])}</td></tr>`).join('')}</tbody></table>` : '<p>Field schema not yet verified.</p>'}</section>
${entry.related ? `<section aria-labelledby="related-heading"><h2 id="related-heading">Related sources</h2><ul>${entry.related.map(value=>`<li>${link(value.url,value.label)}</li>`).join('')}</ul></section>` : ''}
<section aria-labelledby="upkeep-heading"><h2 id="upkeep-heading">Contacts, costs and upkeep</h2><dl class="source-upkeep">${definition('Contact',entry.contact)}${definition('Cost',entry.cost)}${definition('Reuse terms',entry.terms)}${definition('Update frequency',entry.update_frequency)}${definition('Entry maintainer',entry.entry_maintainer)}${definition('Source type',entry.source_type)}</dl></section>
<section aria-labelledby="next-heading"><h2 id="next-heading">Next investigation</h2>${list(entry.next)}</section>
<section aria-labelledby="evidence-heading"><h2 id="evidence-heading">Check evidence</h2><ul>${entry.evidence.map(value=>`<li>${link(value.url,value.note)}</li>`).join('')}</ul></section>
<p class="source-end-links">${link(repo+'/blob/main/sources/'+entry.id+'.json','View entry in GitHub')} · ${link(repo+'/issues/new?template=source-correction.yml','Report a correction')} · ${link('../index.html','Back to directory')}</p></article>`;
  return page({title:entry.title,repo,prefix:'../',content,source:true});
}
